Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
Es = np.arange(0.01, 4.0, 0.0005) #1.6
width_barrier = 0.12
width_gap = 5
Ttrans = np.zeros(Es.size)
i = 0
for E in Es:
    klow = np.emath.sqrt(2 * m * E)
    khigh = np.emath.sqrt(2 * m * (E - Vb))
    res_mat = DMat(klow, khigh) @ PMat(khigh, width_barrier) @ DMat(khigh, klow) @ PMat(klow, width_gap)
    U, V = np.linalg.eig(res_mat)
    diag_res_mat = np.diag([U[0],U[1]])
    res_mat = np.linalg.matrix_power(diag_res_mat,20)
    res_mat = V @ res_mat @ np.linalg.inv(V)
    Ttrans[i] = 1 - np.abs(res_mat[1, 0])**2 / np.abs(res_mat[0,0])**2
    i = i + 1

plt.plot(Es, Ttrans)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m/var/folders/xx/v9dchmf97dd5b8x7jswjw5yc0000gn/T/ipykernel_56369/1337762874.py[0m in [0;36m<module>[0;34m[0m
[1;32m      6[0m [0;32mfor[0m [0mE[0m [0;32min[0m [0mEs[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m      7[0m     [0mklow[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0memath[0m[0;34m.[0m[0msqrt[0m[0;34m([0m[0;36m2[0m [0;34m*[0m [0mm[0m [0;34m*[0m [0mE[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 8[0;31m     [0mkhigh[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0memath[0m[0;34m.[0m[0msqrt[0m[0;34m([0m[0;36m2[0m [0;34m*[0m [0mm[0m [0;34m*[0m [0;34m([0m[0mE[0m [0;34m-[0m [0mVb[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      9[0m     [0mres_mat[0m [0;34m=[0m [0mDMat[0m[0;34m([0m[0mklow[0m[0;34m,[0m [0mkhigh[0m[0;34m)[0m [0;34m@[0m [0mPMat[0m[0;34m([0m[0mkhigh[0m[0;34m,[0m [0mwidth_barrier[0m[0;34m)[0m [0;34m@[0m [0mDMat[0m[0;34m([0m[0mkhigh[0m[0;34m,[0m [0mklow[0m[0;34m)[0m [0;34m@[0m [0mPMat[0m[0;34m([0m[0mklow[0m[0;34m,[0m [0mwidth_gap[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     10[0m     [0mU[0m[0;34m,[0m [0mV[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0mlinalg[0m[0;34m.[0m[0meig[0m[0;34m([0m[0mres_mat[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'Vb' is not defined
NameError: name 'Vb' is not defined

